"""OpenClaw integration package for exScholar."""

from .ingest import (
    DEFAULT_OPENCLAW_CHECK_MODEL,
    DEFAULT_OPENCLAW_CONFIG_PATH,
    DEFAULT_OPENCLAW_FALLBACK_MODEL,
    DEFAULT_OPENCLAW_IMAGE_FALLBACK_MODEL,
    DEFAULT_OPENCLAW_IMAGE_MODEL,
    DEFAULT_OPENCLAW_MODEL,
    OpenClawIngestError,
    answer_question_from_text,
    extract_paper_candidate_from_image,
    extract_metadata_from_text,
    extract_pdf_bundle,
    generate_analysis_from_text,
    resolve_openclaw_model,
)
from .paper_lookup import (
    build_lookup_record,
    find_best_dblp_match,
    find_best_web_match,
    normalize_doi,
    resolve_paper_lookup_from_candidate,
    resolve_paper_lookup_from_image,
    search_paper_candidates_via_web,
    web_result_domain_score,
)

__all__ = [
    "DEFAULT_OPENCLAW_CONFIG_PATH",
    "answer_question_from_text",
    "DEFAULT_OPENCLAW_CHECK_MODEL",
    "DEFAULT_OPENCLAW_FALLBACK_MODEL",
    "DEFAULT_OPENCLAW_IMAGE_FALLBACK_MODEL",
    "DEFAULT_OPENCLAW_IMAGE_MODEL",
    "DEFAULT_OPENCLAW_MODEL",
    "OpenClawIngestError",
    "build_lookup_record",
    "extract_metadata_from_text",
    "extract_paper_candidate_from_image",
    "extract_pdf_bundle",
    "find_best_dblp_match",
    "find_best_web_match",
    "generate_analysis_from_text",
    "normalize_doi",
    "resolve_paper_lookup_from_candidate",
    "resolve_paper_lookup_from_image",
    "resolve_openclaw_model",
    "search_paper_candidates_via_web",
    "web_result_domain_score",
]
